version: "3"
services:
  frontend:
    build: ./frontend
    image: vborregoperez/podcast-app-frontend
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - server
  server:
    build: ./server
    image: vborregoperez/podcast-app-server
    ports:
      - "3050:3050"
    restart: always
